-- Borrado de tablas
DROP TABLE IF EXISTS PRESTAMOS;
DROP TABLE IF EXISTS EJEMPLARES;
DROP TABLE IF EXISTS USUARIOS;
DROP TABLE IF EXISTS PENALIZACIONES;
DROP TABLE IF EXISTS LIBROS_AUTORES;
DROP TABLE IF EXISTS AUTORES;
DROP TABLE IF EXISTS LIBROS;


-- 1. Tabla LIBROS
CREATE TABLE LIBROS (
    ID_LIBRO INT PRIMARY KEY AUTO_INCREMENT,
    TITULO VARCHAR(100) NOT NULL,
    ISBN BIGINT UNIQUE, 
    EDITORIAL VARCHAR(50),
    GENERO VARCHAR(30),
    NUM_COPIAS INT DEFAULT 0
);

-- 2. Tabla AUTORES
CREATE TABLE AUTORES (
    ID_AUTOR INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(50),
    APELLIDOS VARCHAR(50),
    NACIONALIDAD VARCHAR(30)
);

-- 3. Tabla LIBROS_AUTORES (Relación N:M)
CREATE TABLE LIBROS_AUTORES (
    ID_LIBRO INT,
    ID_AUTOR INT,
    PRIMARY KEY (ID_LIBRO, ID_AUTOR),
    CONSTRAINT FK_ID_LIBRO FOREIGN KEY (ID_LIBRO) REFERENCES LIBROS (ID_LIBRO) ON DELETE CASCADE,
    CONSTRAINT FK_ID_AUTOR FOREIGN KEY (ID_AUTOR) REFERENCES AUTORES (ID_AUTOR) ON DELETE CASCADE
);

-- 4. Tabla PENALIZACIONES
CREATE TABLE PENALIZACIONES (
    ID_PENALIZACION INT PRIMARY KEY AUTO_INCREMENT,
    DESCRIPCION VARCHAR(100),
    NUM_DIAS INT
);

-- 5. Tabla USUARIOS
CREATE TABLE USUARIOS (
    ID_USER INT PRIMARY KEY AUTO_INCREMENT,
    DNI_USER VARCHAR(10) UNIQUE,
    NOMBRE_USER VARCHAR(50),
    TELEFONO_USER VARCHAR(15), -- Mejor VARCHAR para teléfonos por formatos e internacionales
    PASSWORD_USER VARCHAR(100),
    NSS BIGINT,
    ID_PENALIZACION INT,
    FECHA_PENALIZACION DATE,
    CONSTRAINT FK_ID_PENALIZACION FOREIGN KEY (ID_PENALIZACION) REFERENCES PENALIZACIONES (ID_PENALIZACION)
);

-- 6. Tabla EJEMPLARES
CREATE TABLE EJEMPLARES (
    ID_EJEMPLAR INT PRIMARY KEY AUTO_INCREMENT,
    ESTADO_FISICO VARCHAR(50),
    ID_LIBRO INT,
    CONSTRAINT FK_COD_LIBRO FOREIGN KEY (ID_LIBRO) REFERENCES LIBROS (ID_LIBRO) ON DELETE CASCADE
);

-- 7. Tabla PRESTAMOS
CREATE TABLE PRESTAMOS (
    ID_PRESTAMO INT PRIMARY KEY AUTO_INCREMENT,
    FECHA_ALQUILER DATE,
    FECHA_DEVOLUCION DATE,
    ID_EJEMPLAR INT,
    ID_USER INT,
    CONSTRAINT FK_ID_USUARIO FOREIGN KEY (ID_USER) REFERENCES USUARIOS (ID_USER),
    CONSTRAINT FK_ID_EJEMPLAR FOREIGN KEY (ID_EJEMPLAR) REFERENCES EJEMPLARES (ID_EJEMPLAR)
);